### ISSUE TITLE
Trsut implimenation Todo/Discussions

### ISSUE THREAD

**Issue by TeoTwawki** [DarkstarProject/darkstar#4746]
- [ ] use a mob family for trust base stats, because some trust don't align with a player race but we can easily have a player race in mob families (in fact we already do) ?
- [ ] load skill lists and spell lists the same as mobs, so we don't need an enum like automatons did?
- [ ] decide if we're going with a general move to using initialization in scritp to set up entities, or if we want to table it. If we table trust data I'm thinking along these lines:
```sql
-- MySQL dump 10.13  Distrib 5.7.12, for Win64 (x86_64)
--
-- Host: localhost    Database: dspdb
-- ------------------------------------------------------
-- Server version	5.5.5-10.0.20-MariaDB

--
-- Table structure for table `trust_data`
--

DROP TABLE IF EXISTS `trust_data`;
CREATE TABLE `trust_data` (
  `trustId` int(10) unsigned NOT NULL,
  `name` varchar(24) DEFAULT NULL,
  `spellId` smallint(3) NOT NULL,
  `mainjob` tinyint(1) unsigned NOT NULL DEFAULT 0,
  `subjob` smallint(3) unsigned NOT NULL,
  `mobFamily` smallint(4) unsigned NOT NULL DEFAULT '0',
  `spellList` smallint(4) NOT NULL DEFAULT 0,
  `skill_list_id` smallint(5) unsigned NOT NULL DEFAULT 0,
  `model` binary(20) NOT NULL,
  PRIMARY KEY (`trustId`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

--
-- Dumping data for table `augments`
--

INSERT INTO `trust_data` VALUES (1,'shantotto',896,4,4,153,666,2000,0x0500B80B00000000000000000000000000000000); -- Test!

-- Dump completed on 2017-12-05  4:18:42
```
